#!/bin/sh

mkdir -p results
n=0
base="oilFlow"
name="results/${base}_${n}"
while [ -d $name ]; do
  n=$(( n + 1 ))
  name="results/${base}_${n}"
done
cp -r org $name

#------------------------------------------------------------------------------
